replicaCount: 1

minio:
  image: "minio/minio"
  tag: "latest"
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  bucketName: "s3wwwbucket"
  storageSize: "10Gi"
  consoleport: ":46119"

s3www:
  image: "spaniard89/s3www-golang"
  tag: "latest"
  port: 8080
  bucket: "s3wwwbucket"
  endpoint: "minio-service:9000"
  address: "0.0.0.0:8080"

loadBalancer:
  enabled: true

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: www.up42exercise.com
      paths: ["/"]
  tls: []

prometheus:
  enabled: true

metrics:
  port: 8080
  path: "/metrics"